BUG: Handle cases where stats are missing
As seen with python dev.py bench -t optimize_linprog where

cmd = ['asv', 'run', '--show-stderr', '--quick'] + bench_args

asv-spyglass to-df benchmarks/results/rgx1gen11/f4546621-virtualenv-py3.12-Cython-meson-python-numpy-pybind11-pytest-pythran.json benchmarks/results/benchmarks.json

Which now works fine, and previously errored out with a TypeError:

    row = {

          ^

TypeError: 'NoneType' object is not a mapping